gameEX = {
        { set = "EX",             name = "The Emperor" },
        { set = "NH",             name = "Temperance" },
        { set = "MS",             name = "Wheel of Fortune" },
        { set = "GV",             name = "The Tower" },
        { set = "VL",             name = "Strength" },
        { set = "DH",             name = "The Devil" },
        { set = "IN",             name = "The Hermit" },
        { set = "AS",             name = "The Magician" },
        { set = "DP",             name = "The Lovers" },
        { set = "EX NH",          name = "A Fair Leader" },
        { set = "EX MS",          name = "Block Rationing" },
        { set = "EX GV",          name = "Invictus" },
        { set = "EX VL",          name = "Icarus" },
        { set = "EX DH",          name = "The Devil's Temptation" },
        { set = "EX IN",          name = "Emperor's Dilemma" },
        { set = "EX AS",          name = "Dancing Queen" },
        { set = "EX DP",          name = "Trained Professionals" },
        { set = "NH MS",          name = "All in" },
        { set = "NH GV",          name = "A Modern Classic" },
        { set = "NH VL",          name = "Resistance" },
        { set = "NH DH",          name = "Purgatory Lite" },
        { set = "NH IN",          name = "Helen Keller" },
        { set = "NH AS",          name = "The Starving Artist" },
        { set = "NH DP",          name = "Hand in Hand" },
        { set = "MS GV",          name = "Cheese Race" },
        { set = "MS VL",          name = "Swiss Cheese" },
        { set = "MS DH",          name = "Dig In" },
        { set = "MS IN",          name = "Blind Bet" },
        { set = "MS AS",          name = "Roulette Wheel" },
        { set = "MS DP",          name = "It's Complicated..." },
        { set = "GV VL",          name = "Comfort Food" },
        { set = "GV DH",          name = "The Speed Demon" },
        { set = "GV IN",          name = "The Grandmaster" },
        { set = "GV AS",          name = "The Juggler" },
        { set = "GV DP",          name = "Heavy Hearts" },
        { set = "VL DH",          name = "Lucifer" },
        { set = "VL IN",          name = "Memorization" },
        { set = "VL AS",          name = "Water From Stone" },
        { set = "DH IN",          name = "The Ghost" },
        { set = "DH AS",          name = "The Deal with the Devil" },
        { set = "DH DP",          name = "Forbidden Lovers" },
        { set = "IN AS",          name = "The Abstract Artist" },
        { set = "IN DP",          name = "Love is Blind" },
        { set = "AS DP",          name = "Collaboration" },
        { set = "EX NH MS",       name = "Online Gambling" },
        { set = "EX NH GV",       name = "Beyond Death" },
        { set = "EX NH VL",       name = "Archangel" },
        { set = "EX NH DH",       name = "Emperor's Decadence" },
        { set = "EX NH IN",       name = "The Friar" },
        { set = "EX NH AS",       name = "Indecision" },
        { set = "EX MS GV",       name = "Mining Operation" },
        { set = "EX MS VL",       name = "The Wolf of Wall Street" },
        { set = "EX MS DH",       name = "No Warning" },
        { set = "EX MS IN",       name = "Irrational" },
        { set = "EX MS AS",       name = "The Rich Gambler" },
        { set = "EX GV VL",       name = "Relaxation" },
        { set = "EX GV DH",       name = "The Daredevil" },
        { set = "EX GV IN",       name = "The Super GM" },
        { set = "EX GV AS",       name = "Master of the T" },
        { set = "EX GV DP",       name = "Sinking" },
        { set = "EX VL DH",       name = "The Mad Lord" },
        { set = "EX VL IN",       name = "Bounty Hunter" },
        { set = "EX VL AS",       name = "The Con Artist" },
        { set = "EX DH IN",       name = "The Architect" },
        { set = "EX DH AS",       name = "Loki" },
        { set = "EX IN AS",       name = "Expertise" },
        { set = "NH MS GV",       name = "Atlas' Burden" },
        { set = "NH MS VL",       name = "The Glass Cannon" },
        { set = "NH MS DH",       name = "Deadlock" },
        { set = "NH MS IN",       name = "The False Prophet" },
        { set = "NH MS AS",       name = "Unpredictable Outcome" },
        { set = "NH GV VL",       name = "Traditional" },
        { set = "NH GV DH",       name = "Unstable Footing" },
        { set = "NH GV IN",       name = "Evanescence" },
        { set = "NH GV AS",       name = "A Modern Twist" },
        { set = "NH GV DP",       name = "Nostalgia" },
        { set = "NH VL DH",       name = "Judgment" },
        { set = "NH VL IN",       name = "Justice" },
        { set = "NH VL AS",       name = "Bob Ross" },
        { set = "NH DH IN",       name = "Blindside" },
        { set = "NH DH AS",       name = "Shapeshifter" },
        { set = "NH IN AS",       name = "The Blind Artist" },
        { set = "NH IN DP",       name = "Left On Read" },
        { set = "MS GV VL",       name = "Survival" },
        { set = "MS GV DH",       name = "Double Down" },
        { set = "MS GV IN",       name = "Burrata" },
        { set = "MS GV AS",       name = "Rough Sketch" },
        { set = "MS VL DH",       name = "Utter Trash" },
        { set = "MS VL IN",       name = "Starstruck" },
        { set = "MS VL AS",       name = "Cream Cheese" },
        { set = "MS VL DP",       name = "Couples Therapy" },
        { set = "MS DH IN",       name = "The Stealth Ninja" },
        { set = "MS DH AS",       name = "The Escape Artist" },
        { set = "MS IN AS",       name = "Abstraction" },
        { set = "GV VL DH",       name = "Temptation" },
        { set = "GV VL IN",       name = "Paranoia" },
        { set = "GV VL AS",       name = "The Gladiator" },
        { set = "GV DH IN",       name = "The Drunk Driver" },
        { set = "GV DH AS",       name = "The Texting Driver" },
        { set = "GV IN AS",       name = "The Spinmaster" },
        { set = "VL DH IN",       name = "The Flickering Spirit" },
        { set = "VL DH AS",       name = "Forbidden Sorcery" },
        { set = "VL IN AS",       name = "Eccentric Recluse" },
        { set = "VL AS DP",       name = "The Cheaters" },
        { set = "DH IN AS",       name = "The Libertine" },
        { set = "DH IN DP",       name = "Separation Anxiety" },
        { set = "EX NH MS GV",    name = "Atlas' Lament" },
        { set = "EX NH MS VL",    name = "The Fugitive" },
        { set = "EX NH MS DH",    name = "Impasse" },
        { set = "EX NH MS AS",    name = "Fair Chance" },
        { set = "EX NH GV VL",    name = "Cutting Edge" },
        { set = "EX NH GV IN",    name = "Still Water" },
        { set = "EX NH GV AS",    name = "Beyond the Afterdeath" },
        { set = "EX NH VL DH",    name = "Azathoth" },
        { set = "EX NH VL IN",    name = "Unreasonable" },
        { set = "EX NH VL AS",    name = "The Scam Leader" },
        { set = "EX NH DH IN",    name = "Invisible Decadence" },
        { set = "EX NH DH AS",    name = "Amorphous" },
        { set = "EX NH IN AS",    name = "Black Magic" },
        { set = "EX NH AS DP",    name = "Royal Waltz" },
        { set = "EX MS GV VL",    name = "Juggernaut" },
        { set = "EX MS GV DH",    name = "Mining for Netherite" },
        { set = "EX MS GV AS",    name = "Irregular Sketch" },
        { set = "EX MS VL DH",    name = "Divine Mastery" },
        { set = "EX MS VL IN",    name = "Interstellar" },
        { set = "EX MS VL AS",    name = "The Hacker" },
        { set = "EX MS DH AS",    name = "Imprisonment" },
        { set = "EX MS IN AS",    name = "The Mathematician" },
        { set = "EX GV VL DH",    name = "The Autocrat" },
        { set = "EX GV VL IN",    name = "Lateness" },
        { set = "EX GV VL AS",    name = "Inertia" },
        { set = "EX GV DH AS",    name = "Spin Overlord" },
        { set = "EX GV IN AS",    name = "Mastermind" },
        { set = "EX VL DH IN",    name = "Corruption" },
        { set = "EX VL DH AS",    name = "Devilish Falsifier" },
        { set = "EX VL IN AS",    name = "Insanity" },
        { set = "EX DH IN AS",    name = "Reverse Quadruple Threat" },
        { set = "NH MS GV VL",    name = "Quadruple threat" },
        { set = "NH MS GV DH",    name = "Futility" },
        { set = "NH MS GV IN",    name = "Spelunking" },
        { set = "NH MS VL DH",    name = "Deadbolt" },
        { set = "NH MS VL IN",    name = "Blind Swinging" },
        { set = "NH MS VL AS",    name = "Bluff" },
        { set = "NH MS DH IN",    name = "Unfinished Business" },
        { set = "NH MS DH AS",    name = "Locksmith" },
        { set = "NH MS IN AS",    name = "Writer's Block" },
        { set = "NH GV VL DH",    name = "Nephalem" },
        { set = "NH GV VL IN",    name = "The Black Hole" },
        { set = "NH GV VL AS",    name = "Recreation" },
        { set = "NH GV DH IN",    name = "Live Fast Die Young" },
        { set = "NH GV DH AS",    name = "Dance Dance Revolution" },
        { set = "NH GV IN AS",    name = "Divine Failure" },
        { set = "NH GV IN DP",    name = "Silver Anniversary" },
        { set = "NH VL DH IN",    name = "Spilled Milk" },
        { set = "NH VL DH AS",    name = "The Restrained Artist" },
        { set = "NH VL IN AS",    name = "Vigilante" },
        { set = "NH DH IN AS",    name = "Impressionism" },
        { set = "MS GV VL DH",    name = "Quadruple Down" },
        { set = "MS GV VL IN",    name = "Eleventh Hour" },
        { set = "MS GV VL AS",    name = "Gambled Faith" },
        { set = "MS GV DH IN",    name = "Intoxication" },
        { set = "MS GV DH AS",    name = "The Spacial Artist" },
        { set = "MS GV IN AS",    name = "Parmigiano Reggiano" },
        { set = "MS VL DH IN",    name = "The Night Watchman" },
        { set = "MS VL DH AS",    name = "Blue Cheese" },
        { set = "MS VL DH DP",    name = "Quadruples Therapy" },
        { set = "MS VL IN AS",    name = "Creative Explosion" },
        { set = "MS DH IN AS",    name = "Nascent" },
        { set = "GV VL DH IN",    name = "Nightmare" },
        { set = "GV VL DH AS",    name = "Sword Box" },
        { set = "GV VL IN AS",    name = "Immense Pressure" },
        { set = "GV DH IN AS",    name = "Horror Thriller" },
        { set = "GV DH IN DP",    name = "Timid Adoration" },
        { set = "VL DH IN AS",    name = "The Prodigy" },
        { set = "EX NH MS GV VL", name = "Oppression" },
        { set = "EX NH MS VL DH", name = "No Holds Barred" },
        { set = "EX NH GV VL DH", name = "The Veteran" },
        { set = "EX NH GV VL IN", name = "Foresight" },
        { set = "EX NH GV DH AS", name = "The Kill Screen" },
        { set = "EX NH GV IN AS", name = "Paragon" },
        { set = "EX NH GV IN DP", name = "Golden Anniversary" },
        { set = "EX NH VL DH IN", name = "Spoiled Milk" },
        { set = "EX NH VL DH AS", name = "Loss of Control" },
        { set = "EX NH VL IN AS", name = "Loading Screen" },
        { set = "EX NH DH IN AS", name = "Futile Spectacle" },
        { set = "EX MS GV VL DH", name = "Hell's Gate" },
        { set = "EX MS GV VL IN", name = "Hunted" },
        { set = "EX MS GV VL AS", name = "Deadline" },
        { set = "EX MS GV DH AS", name = "The Temporal Artist" },
        { set = "EX MS VL DH AS", name = "False Security" },
        { set = "EX MS VL IN AS", name = "Reload" },
        { set = "EX GV VL DH IN", name = "Unexpectancy" },
        { set = "EX GV VL IN AS", name = "Speed the Collapse" },
        { set = "EX VL DH IN AS", name = "Reverse Quintuple Threat" },
        { set = "NH MS GV VL DH", name = "Quintuple threat" },
        { set = "NH MS GV DH IN", name = "Misdrop Haven" },
        { set = "NH MS GV DH AS", name = "A Classic Escape" },
        { set = "NH MS GV IN AS", name = "Lost and Dizzy" },
        { set = "NH MS VL DH IN", name = "Blind Faith" },
        { set = "NH MS VL DH AS", name = "Boltsmith" },
        { set = "NH MS VL IN AS", name = "Ballet Dancing" },
        { set = "NH MS DH IN AS", name = "Disappearance" },
        { set = "NH GV VL DH IN", name = "Entropy" },
        { set = "NH GV VL DH AS", name = "Demonic Possession" },
        { set = "NH GV VL IN AS", name = "Ergosphere" },
        { set = "NH GV DH IN AS", name = "Cheat Code" },
        { set = "NH VL DH IN AS", name = "Magic" },
        { set = "MS GV VL DH IN", name = "Slaughterhouse" },
        { set = "MS GV VL DH AS", name = "Killer Clown" },
        { set = "MS GV VL IN AS", name = "Mortal Chaos" },
        { set = "MS GV DH IN AS", name = "Doubled Symbolism" },
        { set = "MS VL DH IN AS", name = "Beethoven" },
        { set = "GV VL DH IN AS", name = "Lost Genius" },
    }